#!/bin/bash

# postflight script for the MacTeX installer

PKG_PATH=$1
YEAR=2017

SYSVERSION=`/usr/bin/uname -r | /usr/bin/cut -f 1 -d .`
LEGACY_SYSVERSION=13
PROCESSOR=`/usr/bin/uname -m`
PROCESSOR_LINK="$PROCESSOR"
PLATFORM="${PROCESSOR}-darwin"

# 10.6 and later
if [[ "$SYSVERSION" -ge 10 ]]; then
	# 10.6 - 10.9, x86_64
	if [[ "$SYSVERSION" -le "$LEGACY_SYSVERSION" ]] && [[ `sysctl -n hw.cpu64bit_capable` -eq 1 ]]; then
		PROCESSOR="x86_64"
		PROCESSOR_LINK="${PROCESSOR}-legacy"
		PLATFORM="${PROCESSOR}-darwinlegacy"
	fi
fi


# Adjust PATH and MANPATH

# Much of this code was copied from Gerben Wierda long ago.
# Later, Leopard provided more convenient ways to modify the
# PATH, and this is reflected below. The code has not been touched
# since Leopard.

manpath="/Library/TeX/Distributions/.DefaultTeX/Contents/Man"
binpath="/usr/texbin"

# add elements to path and manpath

if [[ ( ! -d /etc/paths.d ) ]]; then
	mkdir /etc/paths.d
fi
cp -f -X ./TeXPath /etc/paths.d/TeX
chown root:wheel /etc/paths.d/TeX
chmod 644 /etc/paths.d/TeX

if [[ ( ! -d /etc/manpaths.d ) ]]; then
	mkdir /etc/manpaths.d
fi
cp -f -X ./TeXManPath /etc/manpaths.d/TeX
chown root:wheel /etc/manpaths.d/TeX
chmod 644 /etc/manpaths.d/TeX


# in Leopard, if /etc/profile or /etc/csh.login do NOT contain a call to path_helper, then use the old modifications
# don't do this in Snow Leopard

if [[ ( "$SYSVERSION" -eq 9 ) ]]; then
if [[ ( -e /etc/profile ) && ( $( grep -c '^[^#]*eval `/usr/libexec/path_helper -s`' /etc/profile ) = 0 ) ]]; then
	./setloginpath $binpath TeX
fi
if [[ ( -e /etc/csh.login ) && ( $( grep -c '^[^#]*eval `/usr/libexec/path_helper -c`' /etc/csh.login ) = 0 ) ]]; then
	./setloginpath $binpath TeX
fi
fi


# Now install the TeX Dist Data Structure and links to it

if [[ ! -d /Library/TeX ]]; then
	mkdir /Library/TeX
fi

if [[ ( !  -L /Library/TeX/texbin ) && ( -d /Library/TeX/texbin ) && ( -e /Library/TeX/texbin/tex ) ]]; then
	rm -R /Library/TeX/texbin
fi

if [[ -L /Library/TeX/texbin ]]; then
	rm /Library/TeX/texbin
fi

if [[ ( "$SYSVERSION" -lt 15 ) && ( !  -L /usr/texbin ) && ( -d /usr/texbin ) && ( -e /usr/texbin/tex ) ]]; then
	rm -R /usr/texbin
fi

if [[ ( "$SYSVERSION" -lt 15 ) && ( -L usr/texbin ) ]]; then
	rm usr/texbin
fi


# NEW STUFF

# In Mavericks and above, /Library/TeX/texbin points to /Library/TeX/Distributions/Programs/texbin
# but that then points to the old location. Jerome understands why!

# I got a new Pref Pane from Jerome just as everythihg else was done and I was on a trip to Seattle.
# I wasn't happy, but I made the change. Since some users will have that version of the Pref Pane,
# perhaps we need to keep this.

# up to 10.8
if [[ "$SYSVERSION" -lt 13 ]]; then
	ln -fhs Distributions/.DefaultTeX/Contents/Programs/texbin /Library/TeX/texbin
	ln -fhs /Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin /usr/texbin
else
	# 10.9 and later
	ln -fhs Distributions/Programs/texbin /Library/TeX/texbin
	# 10.9 and 10.10
	if [[ "$SYSVERSION" -lt 15 ]]; then
		ln -fhs /Library/TeX/Distributions/Programs/texbin /usr/texbin
	fi
fi

# END OF NEW STUFF


# create the texdist structure

if [[ ! -d /Library/TeX ]]; then
	mkdir /Library/TeX
fi


if [[ -L /Library/TeX/Documentation ]]; then
	rm /Library/TeX/Documentation
fi

if [[ ! -e /Library/TeX/Documentation ]]; then
	ln -s Distributions/.DefaultTeX/Contents/Doc /Library/TeX/Documentation
fi

if [[ -L /Library/TeX/Root ]]; then
	rm /Library/TeX/Root
fi

if [[ ! -e /Library/TeX/Root ]]; then
	ln -s Distributions/.DefaultTeX/Contents/Root /Library/TeX/Root
fi

if [[ -L /Library/TeX/Local ]]; then
	rm /Library/TeX/Local
fi

if [[ ! -e /Library/TeX/Local ]]; then
	ln -s Distributions/.DefaultTeX/Contents/TexmfLocal /Library/TeX/Local
fi

if [[ ! -d /Library/TeX/Distributions ]]; then
	mkdir /Library/TeX/Distributions
fi

# NEW STUFF

if [[ ! -d /Library/TeX/Distributions/Programs ]]; then
	mkdir /Library/TeX/Distributions/Programs
	ln -s ../.DefaultTeX/Contents/Programs/texbin /Library/TeX/Distributions/Programs/texbin
fi

# END OF NEW STUFF


if [[ ! -e /Library/TeX/Distributions/TeXDist-description.rtf ]]; then
	cp ./TeXDist-description.rtf /Library/TeX/Distributions/TeXDist-description.rtf
	chmod 644 /Library/TeX/Distributions/TeXDist-description.rtf
fi

if [[  -L /usr/local/bin/texdist ]]; then
	rm /usr/local/bin/texdist
fi

if [[ ! -d /usr/local/bin ]]; then
	mkdir /usr/local/bin
fi

if [[ ! -e /usr/local/bin/texdist ]]; then
	ln -s /Library/TeX/.scripts/texdist /usr/local/bin/texdist
fi



if [[ ! -d /Library/TeX/Distributions/.DefaultTeX ]]; then
	mkdir /Library/TeX/Distributions/.DefaultTeX
fi


# /Library/TeX/Distributions/.DefaultTeX/Contents will become a link to the Contents
# folder of the active distribution. Make TeXLive-YYYY that active distribution
# These are symbolic links, so the linked material will be created later on.

if [[  -L /Library/TeX/Distributions/.DefaultTeX/Contents ]]; then
	rm /Library/TeX/Distributions/.DefaultTeX/Contents
fi

if [[ !  -e /Library/TeX/Distributions/.DefaultTeX/Contents ]]; then
	ln -s  ../TeXLive-${YEAR}.texdist/Contents /Library/TeX/Distributions/.DefaultTeX/Contents
fi


# Now we come to the key data defining the various TeX distributions which can occur.
# It is legal to install this data even if the actual distribution isn't available, because the
# Preference Pane checks to make sure the links point somewhere before using them.

# MacTeX-YYYY only installs data for YYYY, and not for other years.

# The TeX Distribution data is much more elaborate than necessary because Jerome
# Laurens and Gerben Wierda thought of other uses of the data, which front ends haven't
# yet implemented.

# For mysterious reasons, each actual distribution occurs twice. Take for example TeXLive-YYYY.
# In /Library/TeX/Distributions, there is a folder named TeXLive-YYYY.texdist. But there is also
# a hidden folder of distributions, /Library/TeX/Distributions/.FactoryDefaults, and this folder
# contains a folder TeXLive-YYYY as well. Notice that the first name has an extension and the
# second does not.

# The TeXLive-YYYY folder in .FactoryDefaults contains a subfolder named Contents. The
# TeXLive-YYYY.texdist folder in Distributions contains an item named Contents, but this
# item is a symbolic link to the Contents folder in TeXLive-YYYY. Aside from this element,
# TeXLive-YYYY.texdist is empty. All of the interesting links are in
# .FactoryDefaults/TeXLive-YYYY/Contents

# This strange design was required so icons could be assigned to the various distributions,
# but that was never carried out. The extra complications now have no purpose, but they take
# almost no disk space and the only people noticing them are people reading these comments!

# All the items of interest are in /Library/TeX/Distributions/.FactoryDefaults/Contents
# Many of these items are there for future use and aren't currently used by software. The key
# subfolder of Contents for us is named Programs. It contains four links titled i386, ppc, powerpc,
# and x86_64. Each is a link to the actual binary directory of the distribution of indicated type.
# Some of these links might be missing for other distributions, but for TeXLive-YYYY, the
# links i386, ppc, and powerpc all point to universal-darwin, and x86_64 points to x86_64-darwin.
# Incidentally, ppc and powerpc will usually point to the same place; this link is duplicated for
# historical reasons.

# Programs also contains a symbolic link named texdist which points to one of the links
# just described. The Preference Pane may reset this link. For instance, the drop down panel
# allowing the user to choose 32 or 64 bit binaries resets the texdist link.

# There is one other key item. Although Leopard can run 64 bit programs, the TeX Live 64 bit
# programs are compiled on Snow Leopard and require that operating system. Jerome Laurens has
# provided a mechanism for handling that situation. On Mac OS X, the Contents directory can contain
# an Info.plist file. Jerome defined such a plist file which lives the minimal operating version which
# can run particular binaries. This would allow us in the future to compile the 64 bit binaries on Lion
# or another advanced system.

# We first create .FactoryDefaults where the interesting data lives. We usually write data there
# only if it doesn't already exist. But we will rewrite the data for our own distribution.

if [[ ! -d /Library/TeX/Distributions/.FactoryDefaults ]]; then
	mkdir /Library/TeX/Distributions/.FactoryDefaults
fi

if [[ -d /Library/TeX/Distributions/.FactoryDefaults/TeXLive-${YEAR} ]]; then
	rm -R /Library/TeX/Distributions/.FactoryDefaults/TeXLive-${YEAR}
fi

# Next we create links to the main data in .Factory Defaults

if [[ ! -d /Library/TeX/Distributions/TeXLive-${YEAR}.texdist ]]; then
	mkdir -p /Library/TeX/Distributions/TeXLive-${YEAR}.texdist
	ln -s ../.FactoryDefaults/TeXLive-${YEAR}/Contents /Library/TeX/Distributions/TeXLive-${YEAR}.texdist/Contents
fi


# At last! Here's the data!

TL_DIR="/Library/TeX/Distributions/.FactoryDefaults/TeXLive-${YEAR}"
TL_LINK="../../../../../../usr/local/texlive"
TL_LINK_YEAR="${TL_LINK}/${YEAR}"
TL_LINK_LOCAL="${TL_LINK}/texmf-local"

if [[ ! -d "$TL_DIR" ]]; then
	mkdir -p "${TL_DIR}/Contents/AllTexmf"
	mkdir -p "${TL_DIR}/Contents/Doc"
	mkdir -p "${TL_DIR}/Contents/Programs"
	mkdir -p "${TL_DIR}/Contents/Resources"
	mkdir -p "${TL_DIR}/Contents/Resources/English.lproj"

	cp ./TeXDistVersion "${TL_DIR}/Contents/TeXDistVersion"
	chmod 644 "${TL_DIR}/Contents/TeXDistVersion"

	cp ./Description.rtf "${TL_DIR}/Contents/Resources/English.lproj/Description.rtf"
	chmod 644 "${TL_DIR}/Contents/Resources/English.lproj/Description.rtf"

	ln -s "${TL_LINK_YEAR}/texmf-dist/doc/info"        "${TL_DIR}/Contents/Info"
	ln -s "${TL_LINK_YEAR}/texmf-dist/doc/man"         "${TL_DIR}/Contents/Man"
	ln -s "${TL_LINK_YEAR}"                            "${TL_DIR}/Contents/Root"
	ln -s "${TL_LINK_LOCAL}"                           "${TL_DIR}/Contents/TexmfLocal"
	ln -s "${TL_LINK_YEAR}/texmf-var"                  "${TL_DIR}/Contents/TexmfSysVar"
	ln -s "../${TL_LINK_YEAR}/bin/i386-darwin"         "${TL_DIR}/Contents/Programs/i386"
	ln -s "../${TL_LINK_YEAR}/bin/powerpc-darwin"      "${TL_DIR}/Contents/Programs/powerpc"
	ln -s "../${TL_LINK_YEAR}/bin/powerpc-darwin"      "${TL_DIR}/Contents/Programs/ppc"
	ln -s "../${TL_LINK_YEAR}/bin/x86_64-darwinlegacy" "${TL_DIR}/Contents/Programs/x86_64-legacy"
	if [[ "$SYSVERSION" -le "$LEGACY_SYSVERSION" ]]; then
		ln -s x86_64-legacy "${TL_DIR}/Contents/Programs/x86_64"
	else
		ln -s "../${TL_LINK_YEAR}/bin/x86_64-darwin" "${TL_DIR}/Contents/Programs/x86_64"
	fi
	ln -s "../${TL_LINK_YEAR}/texmf-dist/doc"          "${TL_DIR}/Contents/Doc/texmf-dist-doc"
	ln -s "../${TL_LINK_YEAR}/texmf-dist/doc"          "${TL_DIR}/Contents/Doc/texmf-doc"
	ln -s "../${TL_LINK_YEAR}/texmf-dist/doc"          "${TL_DIR}/Contents/Doc/texmf-doc-doc"
	ln -s "../${TL_LINK_YEAR}/texmf-dist/doc"          "${TL_DIR}/Contents/Doc/texmf-var-doc"
	ln -s "../${TL_LINK_YEAR}/texmf-dist"              "${TL_DIR}/Contents/AllTexmf/texmf"
	ln -s "../${TL_LINK_YEAR}/texmf-dist"              "${TL_DIR}/Contents/AllTexmf/texmf-dist"
	ln -s "../${TL_LINK_YEAR}/texmf-dist/doc"          "${TL_DIR}/Contents/AllTexmf/texmf-doc"
	ln -s "../${TL_LINK_YEAR}/texmf-var"               "${TL_DIR}/Contents/AllTexmf/texmf-var"
	ln -s "../${TL_LINK_LOCAL}"                        "${TL_DIR}/Contents/AllTexmf/texmf-local"

#	cp ./PrefPane/Info.plist "${TL_DIR}/Contents/Info.plist"
#	chmod 644 "${TL_DIR}/Contents/Info.plist"
fi

echo "### setting program link ${PROCESSOR_LINK}"
ln -s "$PROCESSOR" "${TL_DIR}/Contents/Programs/texbin"
